_target_: transformers.utils.quantization_config.BitsAndBytesConfig

load_in_4bit: true
load_in_8bit: false
llm_int8_threshold: 6.0
llm_int8_has_fp16_weight: false
bnb_4bit_quant_type: nf4
bnb_4bit_compute_dtype: bfloat16
bnb_4bit_use_double_quant: true
